 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/location_records", type: :request do
  # LocationRecord. As you add validations to LocationRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LocationRecord.create! valid_attributes
      get location_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      location_record = LocationRecord.create! valid_attributes
      get location_record_url(location_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_location_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      location_record = LocationRecord.create! valid_attributes
      get edit_location_record_url(location_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LocationRecord" do
        expect {
          post location_records_url, params: { location_record: valid_attributes }
        }.to change(LocationRecord, :count).by(1)
      end

      it "redirects to the created location_record" do
        post location_records_url, params: { location_record: valid_attributes }
        expect(response).to redirect_to(location_record_url(LocationRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LocationRecord" do
        expect {
          post location_records_url, params: { location_record: invalid_attributes }
        }.to change(LocationRecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post location_records_url, params: { location_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested location_record" do
        location_record = LocationRecord.create! valid_attributes
        patch location_record_url(location_record), params: { location_record: new_attributes }
        location_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the location_record" do
        location_record = LocationRecord.create! valid_attributes
        patch location_record_url(location_record), params: { location_record: new_attributes }
        location_record.reload
        expect(response).to redirect_to(location_record_url(location_record))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        location_record = LocationRecord.create! valid_attributes
        patch location_record_url(location_record), params: { location_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested location_record" do
      location_record = LocationRecord.create! valid_attributes
      expect {
        delete location_record_url(location_record)
      }.to change(LocationRecord, :count).by(-1)
    end

    it "redirects to the location_records list" do
      location_record = LocationRecord.create! valid_attributes
      delete location_record_url(location_record)
      expect(response).to redirect_to(location_records_url)
    end
  end
end
